Fix exception when master_type=disable
The following exception occasionally occurs when `master_type=disable`:

```
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1989,
  in handle_event
    self._fire_master(data['data'], data['tag'], data['events'],
    data['pretag'])
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1261, in
  _fire_master
    'tok': self.tok}
AttributeError: 'Minion' object has no attribute 'tok'
```

This occurs because it tries to fire a master event when the minion
is not connected to the master, in this case due to an action from a
beacon.

Signed-off-by: Sergey Kizunov <sergey.kizunov@ni.com>