Prevent backtrace (KeyError) in `ssh_known_hosts.present` state
When using `test=true`, the `ssh_known_hosts.present` state will run
into a backtrace because of an KeyError. Prevent that.
```
An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1591, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/states/ssh_known_hosts.py", line 122, in present
    config=config)
  File "/usr/lib/python2.7/site-packages/salt/modules/ssh.py", line 827, in check_known_host
    return ('exists' if fingerprint == known_host['fingerprint']
KeyError: 'fingerprint'
```