Apparenlty that import is required, otherwise we get stack traces like:
```
Process MWorker-5:36:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/mp/Devel/salt/salt/master.py", line 837, in run
    self.crypticle)
  File "/home/mp/Devel/salt/salt/master.py", line 1527, in __init__
    self.local = salt.client.get_local_client(self.opts['conf_file'])
  File "/home/mp/Devel/salt/salt/client/__init__.py", line 79, in get_local_client
    opts = salt.config.client_config(c_path)
UnboundLocalError: local variable 'salt' referenced before assignment
[INFO    ] Process <class 'salt.master.MWorker'> (14420) died with exit status None, restarting...
^CProcess EventReturn-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
```

Revert "Fix #11365"

This reverts commit f0e4b79142fea2797a4ce874eb3a40c3944e43dc.