Unbreak creating etherstubs on SmartOS
SmartOS (no longer?) handles setting an MTU for etherstub devices,
so silently drop it in order to maintain the current API.

salt:2066 salt % doas salt-ssh smartos-gz nictagadm.add storage0 etherstub
smartos-gz:
    ----------
    Error:
        Error: Cannot specify MTU for local nic tag

Also fixup two examples while here which failed to run and use
format() in a consistent manner.

Tested on SmartOS 20160204T080230Z and 20180203T031130Z