Fix a misplaced `continue` on the grains matching logic which caused a traceback.
```
[21:18:46,004 [salt.utils.minions                          :200 ][ERROR   ] Failed matching available minions with grain pattern: planets:saturn
Traceback (most recent call last):
  File "/home/ubuntu/salt/salt/utils/minions.py", line 197, in check_minions
      }[expr_form](expr)
        File "/home/ubuntu/salt/salt/utils/minions.py", line 119, in _check_grain_minions
    str(match.lower()),
    AttributeError: 'list' object has no attribute 'lower'
```