doc: Define fake version for msgpack and psutil
When using Python 3 to generate the documentation, it will fail:

$ make -C doc html SPHINXBUILD=/usr/share/sphinx/scripts/python3/sphinx-build
[...]
  File "salt/config/__init__.py", line 84, in _gather_buffer_space
    if HAS_PSUTIL and psutil.version_info >= (0, 6, 0):
TypeError: '>=' not supported between instances of 'Mock' and 'tuple'

Therefore add fake version variables to the mocked msgpack and psutil
module.

Signed-off-by: Benjamin Drung <benjamin.drung@profitbricks.com>