Improve __virtual__ checks in sensehat module
If the `sense_hat` python library is installed on the Raspberry Pi, but the
Pi doesn't actually have a SenseHat available, the execution module will
stacktrace when it's loaded:

```
root@raspberrypi:/home/pi# salt-call --local sys.doc none
[ERROR   ] Failed to import module sensehat, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1411, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/sensehat.py", line 26, in <module>
    _sensehat = SenseHat()
  File "/usr/lib/python2.7/dist-packages/sense_hat/sense_hat.py", line 36, in __init__
    raise OSError('Cannot detect %s device' % self.SENSE_HAT_FB_NAME)
OSError: Cannot detect RPi-Sense FB device
local:
    ----------
```

We need to catch the OSError and warn people that this module needs a SenseHat
available to the Pi to work.

This PR catches that OSError in the `__virtual__()` and displays a helpful message to
the user.

This change also helps distinguish the errors of when the `sense_hat` python lib is
missing vs the actual SenseHat missing.