Fix Python3 comparison `TypeError` in `salt.modules.upstart`
Use `len()` to determine emptiness of a dictionary.

PR#44624 introduced a Python3 incompatible comparison where a dict is
compared against an integer, causing breakage on Ubuntu 18.04/bionic
which uses Python3 by default for SaltStack:

```
File "/usr/lib/python3/dist-packages/salt/modules/upstart.py", line 100, in _find_utmp
  if result > 0:
TypeError: '>' not supported between instances of 'dict' and 'int'
```