Fix for malformed SLS files crashing reactor
Before if you had a malformed SLS file you'd get something like:

```
Process Reactor-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/home/thjackso/src/salt-github/salt/utils/event.py", line 688, in run
    self.call_reactions(chunks)
  File "/home/thjackso/src/salt-github/salt/utils/event.py", line 674, in call_reactions
    self.wrap.run(chunk)
  File "/home/thjackso/src/salt-github/salt/utils/event.py", line 713, in run
    l_fun = getattr(self, low['state'])
TypeError: string indices must be integers, not str
[INFO    ] Process <class 'salt.utils.event.Reactor'> (7656) died with exit status None, restarting...
```

Now you get something like:
```
[ERROR   ] Unable to render reactions for event salt/job/20141204195047408340/new due to errors (['The type broken in runner is not formatted as a dictionary']) in one or more of the sls files (['/tmp/test.sls', '/tmp/test2.sls'])
```