Skip random.org tests for any communication failure
This test connects to random.org, which may throws the following error
on one network I manage:

ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

Other errors are possible, such as `socket.error`.  Since it is
difficult to anticipate the failure mode, skip these tests if https
communication provokes any exception.

Also, this is not a unit test--it's more of a system test. My
recommendation that we recategorize this as an integration test where
global IPv4 routing can more reasonably expected.