Handle OSError, you will get this because the signal handler interrupts the systemcall to avoid traces like:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/home/thjackso/src/salt/salt/master.py", line 308, in run_reqserver
    reqserv.run()
  File "/home/thjackso/src/salt/salt/master.py", line 506, in run
    self.__bind()
  File "/home/thjackso/src/salt/salt/master.py", line 500, in __bind
    self.process_manager.run()
  File "/home/thjackso/src/salt/salt/utils/process.py", line 180, in run
    pid, exit_status = os.wait()
OSError: [Errno 4] Interrupted system call
```