Do not fail reading/writing persistent modules when _get_modules_conf() file doesn't exist.
For instance on Arch, /etc/modules-load.d/salt_managed.conf will not exist at first and trying to apply a state such as

microcode:
  kmod.present:
    - persist: True

will fail with the error:
IOError: [Errno 2] No such file or directory: '/etc/modules-load.d/salt_managed.conf'