fix for ping_on_rotate not in config
Since this isn't a default (in config.py), if you didn't set it you get backtraces from _clear_old_jobs:

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/home/thjackso/src/salt-github/salt/master.py", line 162, in _clear_old_jobs
    if self.opts['ping_on_rotate']:
KeyError: 'ping_on_rotate'
```