Fix unbound local variable error
I have occasionally come across this error while running a salt-minion on
Windows using Python 3.5.1 and the TCP transport:

'''
  File "...\salt\crypt.py", line 498, in _authenticate
    if not error:
UnboundLocalError: local variable 'error' referenced before assignment
[WARNING ] Minion received a SIGINT. Exiting.
'''

It seems like there is an overloaded use of the local variable called
`error`, each use with a different lifespan. Changed it so that `error`
is no longer overloaded. This has fixed the issue.

Signed-off-by: Sergey Kizunov <sergey.kizunov@ni.com>