Fixed invalid host causing 'reference to variable before assignment'
The current version of exception handling for network.connect references variable '_address', but '_address' is not defined if a call to socket.getaddrinfo failed in the same try block.

eg.
>salt '<minion>' network.connect junkdomain 80
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1071, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/network.py", line 1104, in connect
        ret['comment'] = 'Unable to connect to {0} ({1}) on {2} port {3}'.format(host, _address[0], proto, port)
    UnboundLocalError: local variable '_address' referenced before assignment

This patch catches socket.getaddrinfo execption socket.gaierror and returns with a friendly fail message.