doc: Mock keyring module import
The salt/sdb/keyring_db.py

Traceback (most recent call last):
  File "salt/sdb/keyring_db.py", line 53, in <module>
    import keyring
  File "/usr/lib/python2.7/dist-packages/keyring/__init__.py", line 6, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 148, in <module>
    init_backend()
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 64, in init_backend
    keyrings = filter(limit, backend.get_all_keyring())
  File "/usr/lib/python2.7/dist-packages/keyring/util/__init__.py", line 20, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 191, in get_all_keyring
    exceptions=TypeError))
  File "/usr/lib/python2.7/dist-packages/keyring/util/__init__.py", line 29, in suppress_exceptions
    for callable in callables:
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 183, in is_class_viable
    keyring_cls.priority
  File "/usr/lib/python2.7/dist-packages/keyring/util/properties.py", line 22, in __get__
    return self.fget.__get__(None, owner)()
  File "/usr/lib/python2.7/dist-packages/keyring/backends/kwallet.py", line 128, in priority
    return super(DBusKeyringKWallet4, cls).priority - 1
  File "/usr/lib/python2.7/dist-packages/keyring/util/properties.py", line 22, in __get__
    return self.fget.__get__(None, owner)()
  File "/usr/lib/python2.7/dist-packages/keyring/backends/kwallet.py", line 31, in priority
    bus = dbus.SessionBus(mainloop=DBusGMainLoop())
NameError: global name 'DBusGMainLoop' is not defined

Therefore also mock the keyring module when generating the
documentation. This fixes #45072.

Signed-off-by: Benjamin Drung <benjamin.drung@profitbricks.com>