states: glance: handle image list instead of dict
glance.image_list now returns a list of images instead of a dict, but
the glance state tried to use the values() method on it either way,
leading to the following exception:

  An exception occurred in this state: Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
      **cdata['kwargs'])
    File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1652, in wrapper
      return f(*args, **kwargs)
    File "/usr/lib/python2.7/dist-packages/salt/states/glance.py", line 155, in image_present
      image, msg = _find_image(name)
    File "/usr/lib/python2.7/dist-packages/salt/states/glance.py", line 60, in _find_image
      return images_dict.values()[0], 'Found image {0}'.format(name)
  AttributeError: 'list' object has no attribute 'values'

This commit makes sure that we're always working with a list, even if
glance.image_list returns a dict.