Fix at.atq support on FreeBSD. This also unbreaks at job creation with at.at.
Given:
```
root@minion2:~ # atq
Date                            Owner           Queue   Job#
Fri Apr  6 23:18:00 UTC 2018    root            c       4
root@minion2:~ #
```

Running at.atq on this minion will fail:
```
root@master:~ # salt 'minion2' at.atq

minion2:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/salt/minion.py", line 1493, in _thread_return
        return_data = executor.execute()
      File "/usr/local/lib/python3.6/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.6/site-packages/salt/modules/at.py", line 110, in atq
        job = tmp[6]
    IndexError: list index out of range
root@master:~ #
```

This patch seems to make it work:
```
root@master:~ # salt 'minion1' at.atq

minion1:
    ----------
    jobs:
        |_
          ----------
          date:
              2018-04-06
          job:
              7
          queue:
              c
          tag:
          time:
              23:42:00
          user:
              root
root@master:~ #
```

Tested against:
```
root@minion1:~ # uname -r
11.1-RELEASE-p9
root@minion1:~ # pkg info | grep salt
py36-salt-2017.7.4_1           Distributed remote execution and configuration management system
root@minion1:~ #
```