joyent: Properly handle error if deployment fails
Previous behavior if an invalid profile parameter was used:

TypeError: 'NoneType' object has no attribute '__getitem__'

New Behavior:

Error: There was a profile error: Failed to deploy VM

Also fix up some pylint complaints