Added skip test_ext_pillar_env_mapping if git module does not exist.
If module named git does not exist, test test_ext_pillar_env_mapping
fail:

======================================================================
ERROR: test_ext_pillar_env_mapping
(integration.modules.pillar.PillarModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/git/salt/tests/integration/modules/pillar.py", line 120, in
test_ext_pillar_env_mapping
    import git
ImportError: No module named git

Added skip test_ext_pillar_env_mapping test.